# Generated by Django 2.2.5 on 2020-01-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='first_app.Webpage'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(default=None, max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='first_app.Topic'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.URLField(default=None, unique=True),
        ),
    ]
