# Generated by Django 2.2.5 on 2020-01-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_cekim_formu_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cekim_formu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
