# Generated by Django 2.2.5 on 2020-01-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20200112_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='witdrawal_form',
            name='status',
        ),
        migrations.AlterField(
            model_name='witdrawal_form',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
