# Generated by Django 2.2.5 on 2020-01-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20200113_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witdrawal_form',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
