# Generated by Django 2.2.5 on 2020-01-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20200113_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='witdrawal_form',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
