# Generated by Django 2.2.5 on 2020-04-13 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_deposit_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit_form',
            name='amount',
        ),
    ]
