# Generated by Django 2.2.5 on 2020-04-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_remove_deposit_form_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit_form',
            name='amount',
            field=models.IntegerField(default=None),
        ),
    ]
