# Generated by Django 2.2.5 on 2020-04-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_deposit_form_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_form',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
