# Generated by Django 2.2.5 on 2020-04-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0019_auto_20200416_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witdrawal_form',
            name='amount',
            field=models.IntegerField(default=True),
        ),
    ]
