# Generated by Django 2.2.5 on 2020-04-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0023_auto_20200416_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_form',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
