# Generated by Django 2.2.5 on 2020-04-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0027_auto_20200416_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit_form',
            old_name='amount',
            new_name='amounts',
        ),
    ]
