# Generated by Django 2.2.5 on 2020-04-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0028_auto_20200416_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit_form',
            name='amounts',
        ),
        migrations.AddField(
            model_name='deposit_form',
            name='amount',
            field=models.IntegerField(default=True),
        ),
    ]
