# Generated by Django 2.2.5 on 2020-04-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0033_sum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sum',
        ),
    ]
