# Generated by Django 2.2.5 on 2020-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0034_delete_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit_form',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='witdrawal_form',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deposit_form',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='In Progress', max_length=15),
        ),
    ]
