# Generated by Django 2.2.5 on 2020-04-28 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0039_auto_20200428_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_form',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='witdrawal_form',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
