# Generated by Django 2.2.5 on 2020-04-28 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0041_auto_20200428_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_form',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 18, 28, 15, 764859, tzinfo=utc), verbose_name='%d.%m.%y %H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='witdrawal_form',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 18, 28, 15, 764357, tzinfo=utc), verbose_name='%d.%m.%y %H:%M:%S'),
        ),
    ]
