# Generated by Django 2.2.5 on 2020-04-28 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0042_auto_20200428_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_form',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 18, 33, 35, 132723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='witdrawal_form',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 18, 33, 35, 132261, tzinfo=utc)),
        ),
    ]
