# Generated by Django 2.2.5 on 2020-04-29 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0047_auto_20200429_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_form',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='%d.%m.%Y %H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='witdrawal_form',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='%d.%m.%Y %H:%M:%S'),
        ),
    ]
