# Generated by Django 2.2.5 on 2020-04-29 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0048_auto_20200429_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_form',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='witdrawal_form',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
