# Generated by Django 3.0.6 on 2020-06-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0057_auto_20200618_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witdrawal_form',
            name='mail',
            field=models.EmailField(max_length=50),
        ),
    ]
