# Generated by Django 3.0.6 on 2020-06-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0062_auto_20200618_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='witdrawal_form',
            name='mail',
        ),
    ]
