# Generated by Django 3.0.6 on 2020-06-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0063_remove_witdrawal_form_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='witdrawal_form',
            name='mail',
            field=models.EmailField(default=None, max_length=50),
        ),
    ]
