# Generated by Django 3.0.6 on 2020-06-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0064_witdrawal_form_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witdrawal_form',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=50),
        ),
    ]
