# Generated by Django 3.0.6 on 2020-06-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0066_auto_20200618_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witdrawal_form',
            name='iban',
            field=models.CharField(blank=True, max_length=26),
        ),
    ]
