# Generated by Django 3.0.6 on 2020-06-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0068_auto_20200618_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witdrawal_form',
            name='mail',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
